return  T{
    [0] = { name = 'KO', excluded = T{false} },
	[1] = { name = 'Weakness', excluded = T{false} },
	[2] = { name = 'Sleep', excluded = T{false} },
	[3] = { name = 'Poison', excluded = T{false} },
	[4] = { name = 'Paralysis', excluded = T{false} },
	[5] = { name = 'Blindness', excluded = T{false} },
	[6] = { name = 'Silence', excluded = T{false} },
	[7] = { name = 'Petrification', excluded = T{false} },
	[8] = { name = 'Disease', excluded = T{false} },
	[9] = { name = 'Curse', excluded = T{false} },
	[10] = { name = 'Stun', excluded = T{false} },
	[11] = { name = 'Bind', excluded = T{false} },
	[12] = { name = 'Weight', excluded = T{false} },
	[13] = { name = 'Slow', excluded = T{false} },
	[14] = { name = 'Charm', excluded = T{false} },
	[15] = { name = 'Doom', excluded = T{false} },
	[16] = { name = 'Amnesia', excluded = T{false} },
	[17] = { name = 'Charm', excluded = T{false} },
	[18] = { name = 'Gradual petrification', excluded = T{false} },
	[19] = { name = 'Sleep', excluded = T{false} },
	[20] = { name = 'Curse', excluded = T{false} },
	[21] = { name = 'Addle', excluded = T{false} },
	[22] = { name = 'Intimidate', excluded = T{false} },
	[23] = { name = 'Kaustra', excluded = T{false} },
	[24] = { name = 'ST24', excluded = T{true} },
	[25] = { name = 'ST25', excluded = T{true} },
	[26] = { name = 'ST26', excluded = T{true} },
	[27] = { name = 'ST27', excluded = T{true} },
	[28] = { name = 'Terror', excluded = T{false} },
	[29] = { name = 'Mute', excluded = T{false} },
	[30] = { name = 'Bane', excluded = T{false} },
	[31] = { name = 'Plague', excluded = T{false} },
	[32] = { name = 'Flee', excluded = T{false} },
	[33] = { name = 'Haste', excluded = T{false} },
	[34] = { name = 'Blaze Spikes', excluded = T{true} },
	[35] = { name = 'Ice Spikes', excluded = T{true} },
	[36] = { name = 'Blink', excluded = T{false} },
	[37] = { name = 'Stoneskin', excluded = T{false} },
	[38] = { name = 'Shock Spikes', excluded = T{true} },
	[39] = { name = 'Aquaveil', excluded = T{false} },
	[40] = { name = 'Protect', excluded = T{false} },
	[41] = { name = 'Shell', excluded = T{false} },
	[42] = { name = 'Regen', excluded = T{false} },
	[43] = { name = 'Refresh', excluded = T{false} },
	[44] = { name = 'Mighty Strikes', excluded = T{false} },
	[45] = { name = 'Boost', excluded = T{true} },
	[46] = { name = 'Hundred Fists', excluded = T{false} },
	[47] = { name = 'Manafont', excluded = T{true} },
	[48] = { name = 'Chainspell', excluded = T{false} },
	[49] = { name = 'Perfect Dodge', excluded = T{false} },
	[50] = { name = 'Invincible', excluded = T{false} },
	[51] = { name = 'Blood Weapon', excluded = T{false} },
	[52] = { name = 'Soul Voice', excluded = T{false} },
	[53] = { name = 'Eagle Eye Shot', excluded = T{false} },
	[54] = { name = 'Meikyo Shisui', excluded = T{false} },
	[55] = { name = 'Astral Flow', excluded = T{false} },
	[56] = { name = 'Berserk', excluded = T{true} },
	[57] = { name = 'Defender', excluded = T{true} },
	[58] = { name = 'Aggressor', excluded = T{true} },
	[59] = { name = 'Focus', excluded = T{true} },
	[60] = { name = 'Dodge', excluded = T{true} },
	[61] = { name = 'Counterstance', excluded = T{true} },
	[62] = { name = 'Sentinel', excluded = T{true} },
	[63] = { name = 'Souleater', excluded = T{false} },
	[64] = { name = 'Last Resort', excluded = T{true} },
	[65] = { name = 'Sneak Attack', excluded = T{false} },
	[66] = { name = 'Copy Image', excluded = T{false} },
	[67] = { name = 'Third Eye', excluded = T{false} },
	[68] = { name = 'Warcry', excluded = T{false} },
	[69] = { name = 'Invisible', excluded = T{false} },
	[70] = { name = 'Deodorize', excluded = T{false} },
	[71] = { name = 'Sneak', excluded = T{false} },
	[72] = { name = 'Sharpshot', excluded = T{true} },
	[73] = { name = 'Barrage', excluded = T{true} },
	[74] = { name = 'Holy Circle', excluded = T{false} },
	[75] = { name = 'Arcane Circle', excluded = T{false} },
	[76] = { name = 'Hide', excluded = T{true} },
	[77] = { name = 'Camouflage', excluded = T{true} },
	[78] = { name = 'Divine Seal', excluded = T{true} },
	[79] = { name = 'Elemental Seal', excluded = T{true} },
	[80] = { name = 'STR Boost', excluded = T{true} },
	[81] = { name = 'DEX Boost', excluded = T{true} },
	[82] = { name = 'VIT Boost', excluded = T{true} },
	[83] = { name = 'AGI Boost', excluded = T{true} },
	[84] = { name = 'INT Boost', excluded = T{true} },
	[85] = { name = 'MND Boost', excluded = T{true} },
	[86] = { name = 'CHR Boost', excluded = T{true} },
	[87] = { name = 'Trick Attack', excluded = T{true} },
	[88] = { name = 'Max HP Boost', excluded = T{fatruelse} },
	[89] = { name = 'Max MP Boost', excluded = T{true} },
	[90] = { name = 'Accuracy Boost', excluded = T{true} },
	[91] = { name = 'Attack Boost', excluded = T{true} },
	[92] = { name = 'Evasion Boost', excluded = T{true} },
	[93] = { name = 'Defense Boost', excluded = T{true} },
	[94] = { name = 'Enfire', excluded = T{true} },
	[95] = { name = 'Enblizzard', excluded = T{true} },
	[96] = { name = 'Enaero', excluded = T{true} },
	[97] = { name = 'Enstone', excluded = T{true} },
	[98] = { name = 'Enthunder', excluded = T{true} },
	[99] = { name = 'Enwater', excluded = T{true} },
	[100] = { name = 'Barfire', excluded = T{false} },
	[101] = { name = 'Barblizzard', excluded = T{false} },
	[102] = { name = 'Baraero', excluded = T{false} },
	[103] = { name = 'Barstone', excluded = T{false} },
	[104] = { name = 'Barthunder', excluded = T{false} },
	[105] = { name = 'Barwater', excluded = T{false} },
	[106] = { name = 'Barsleep', excluded = T{false} },
	[107] = { name = 'Barpoison', excluded = T{false} },
	[108] = { name = 'Barparalyze', excluded = T{false} },
	[109] = { name = 'Barblind', excluded = T{false} },
	[110] = { name = 'Barsilence', excluded = T{false} },
	[111] = { name = 'Barpetrify', excluded = T{false} },
	[112] = { name = 'Barvirus', excluded = T{false} },
	[113] = { name = 'Reraise', excluded = T{false} },
	[114] = { name = 'Cover', excluded = T{false} },
	[115] = { name = 'Unlimited Shot', excluded = T{true} },
	[116] = { name = 'Phalanx', excluded = T{false} },
	[117] = { name = 'Warding Circle', excluded = T{false} },
	[118] = { name = 'Ancient Circle', excluded = T{false} },
	[119] = { name = 'STR Boost', excluded = T{true} },
	[120] = { name = 'DEX Boost', excluded = T{true} },
	[121] = { name = 'VIT Boost', excluded = T{true} },
	[122] = { name = 'AGI Boost', excluded = T{true} },
	[123] = { name = 'INT Boost', excluded = T{true} },
	[124] = { name = 'MND Boost', excluded = T{true} },
	[125] = { name = 'CHR Boost', excluded = T{true} },
	[126] = { name = 'Spirit Surge', excluded = T{false} },
	[127] = { name = 'Costume', excluded = T{true} },
	[128] = { name = 'Burn', excluded = T{false} },
	[129] = { name = 'Frost', excluded = T{false} },
	[130] = { name = 'Choke', excluded = T{false} },
	[131] = { name = 'Rasp', excluded = T{false} },
	[132] = { name = 'Shock', excluded = T{false} },
	[133] = { name = 'Drown', excluded = T{false} },
	[134] = { name = 'Dia', excluded = T{false} },
	[135] = { name = 'Bio', excluded = T{false} },
	[136] = { name = 'STR Down', excluded = T{false} },
	[137] = { name = 'DEX Down', excluded = T{false} },
	[138] = { name = 'VIT Down', excluded = T{false} },
	[139] = { name = 'AGI Down', excluded = T{false} },
	[140] = { name = 'INT Down', excluded = T{false} },
	[141] = { name = 'MND Down', excluded = T{false} },
	[142] = { name = 'CHR Down', excluded = T{false} },
	[143] = { name = 'Level Restriction', excluded = T{true} },
	[144] = { name = 'Max HP Down', excluded = T{false} },
	[145] = { name = 'Max MP Down', excluded = T{false} },
	[146] = { name = 'Accuracy Down', excluded = T{false} },
	[147] = { name = 'Attack Down', excluded = T{false} },
	[148] = { name = 'Evasion Down', excluded = T{false} },
	[149] = { name = 'Defense Down', excluded = T{false} },
	[150] = { name = 'Physical Shield', excluded = T{true} },
	[151] = { name = 'Arrow Shield', excluded = T{true} },
	[152] = { name = 'Magic Shield', excluded = T{true} },
	[153] = { name = 'Damage Spikes', excluded = T{true} },
	[154] = { name = 'Shining Ruby', excluded = T{false} },
	[155] = { name = 'medicine', excluded = T{true} },
	[156] = { name = 'Flash', excluded = T{false} },
	[157] = { name = 'SJ Restriction', excluded = T{true} },
	[158] = { name = 'Provoke', excluded = T{true} },
	[159] = { name = 'Penalty', excluded = T{true} },
	[160] = { name = 'Preparations', excluded = T{true} },
	[161] = { name = 'Sprint', excluded = T{true} },
	[162] = { name = 'Enchantment', excluded = T{true} },
	[163] = { name = 'Azure Lore', excluded = T{false} },
	[164] = { name = 'Chain Affinity', excluded = T{true} },
	[165] = { name = 'Burst Affinity', excluded = T{true} },
	[166] = { name = 'Overdrive', excluded = T{false} },
	[167] = { name = 'Magic Def. Down', excluded = T{false} },
	[168] = { name = 'Inhibit TP', excluded = T{true} },
	[169] = { name = 'Potency', excluded = T{false} },
	[170] = { name = 'Regain', excluded = T{false} },
	[171] = { name = 'Pax', excluded = T{false} },
	[172] = { name = 'Intension', excluded = T{true} },
	[173] = { name = 'Dread Spikes', excluded = T{true} },
	[174] = { name = 'Magic Acc. Down', excluded = T{false} },
	[175] = { name = 'Magic Atk. Down', excluded = T{false} },
	[176] = { name = 'Quickening', excluded = T{true} },
	[177] = { name = 'Encumbrance', excluded = T{true} },
	[178] = { name = 'Firestorm', excluded = T{true} },
	[179] = { name = 'Hailstorm', excluded = T{true} },
	[180] = { name = 'Windstorm', excluded = T{true} },
	[181] = { name = 'Sandstorm', excluded = T{true} },
	[182] = { name = 'Thunderstorm', excluded = T{true} },
	[183] = { name = 'Rainstorm', excluded = T{true} },
	[184] = { name = 'Aurorastorm', excluded = T{true} },
	[185] = { name = 'Voidstorm', excluded = T{true} },
	[186] = { name = 'Helix', excluded = T{false} },
	[187] = { name = 'Sublimation: Activated', excluded = T{false} },
	[188] = { name = 'Sublimation: Complete', excluded = T{false} },
	[189] = { name = 'Max TP Down', excluded = T{false} },
	[190] = { name = 'Magic Atk. Boost', excluded = T{true} },
	[191] = { name = 'Magic Def. Boost', excluded = T{true} },
	[192] = { name = 'Requiem', excluded = T{false} },
	[193] = { name = 'Lullaby', excluded = T{false} },
	[194] = { name = 'Elegy', excluded = T{false} },
	[195] = { name = 'Paeon', excluded = T{false} },
	[196] = { name = 'Ballad', excluded = T{false} },
	[197] = { name = 'Minne', excluded = T{false} },
	[198] = { name = 'Minuet', excluded = T{false} },
	[199] = { name = 'Madrigal', excluded = T{false} },
	[200] = { name = 'Prelude', excluded = T{false} },
	[201] = { name = 'Mambo', excluded = T{false} },
	[202] = { name = 'Aubade', excluded = T{false} },
	[203] = { name = 'Pastoral', excluded = T{false} },
	[204] = { name = 'Hum', excluded = T{false} },
	[205] = { name = 'Fantasia', excluded = T{false} },
	[206] = { name = 'Operetta', excluded = T{false} },
	[207] = { name = 'Capriccio', excluded = T{false} },
	[208] = { name = 'Serenade', excluded = T{false} },
	[209] = { name = 'Round', excluded = T{false} },
	[210] = { name = 'Gavotte', excluded = T{false} },
	[211] = { name = 'Fugue', excluded = T{false} },
	[212] = { name = 'Rhapsody', excluded = T{false} },
	[213] = { name = 'Aria', excluded = T{false} },
	[214] = { name = 'March', excluded = T{false} },
	[215] = { name = 'Etude', excluded = T{false} },
	[216] = { name = 'Carol', excluded = T{false} },
	[217] = { name = 'Threnody', excluded = T{false} },
	[218] = { name = 'Hymnus', excluded = T{false} },
	[219] = { name = 'Mazurka', excluded = T{false} },
	[220] = { name = 'Sirvente', excluded = T{false} },
	[221] = { name = 'Dirge', excluded = T{false} },
	[222] = { name = 'Scherzo', excluded = T{false} },
	[223] = { name = 'Nocturne', excluded = T{false} },
	[224] = { name = 'ST224', excluded = T{true} },
	[225] = { name = 'ST225', excluded = T{true} },
	[226] = { name = 'ST226', excluded = T{true} },
	[227] = { name = 'Store TP', excluded = T{true} },
	[228] = { name = 'Embrava', excluded = T{false} },
	[229] = { name = 'Manawell', excluded = T{true} },
	[230] = { name = 'Spontaneity', excluded = T{false} },
	[231] = { name = 'Marcato', excluded = T{true} },
	[232] = { name = '(N/A)', excluded = T{true} },
	[233] = { name = 'Auto-Regen', excluded = T{false} },
	[234] = { name = 'Auto-Refresh', excluded = T{false} },
	[235] = { name = 'Fishing Imagery', excluded = T{true} },
	[236] = { name = 'Woodworking Imagery', excluded = T{true} },
	[237] = { name = 'Smithing Imagery', excluded = T{true} },
	[238] = { name = 'Goldsmithing Imagery', excluded = T{true} },
	[239] = { name = 'Clothcraft Imagery', excluded = T{true} },
	[240] = { name = 'Leathercraft Imagery', excluded = T{true} },
	[241] = { name = 'Bonecraft Imagery', excluded = T{true} },
	[242] = { name = 'Alchemy Imagery', excluded = T{true} },
	[243] = { name = 'Cooking Imagery', excluded = T{true} },
	[249] = { name = 'Dedication', excluded = T{false} },
	[250] = { name = 'EF Badge', excluded = T{true} },
	[251] = { name = 'Food', excluded = T{false} },
	[252] = { name = 'Mounted', excluded = T{false} },
	[253] = { name = 'Signet', excluded = T{true} },
	[254] = { name = 'Battlefield', excluded = T{true} },
	[256] = { name = 'Sanction', excluded = T{true} },
	[257] = { name = 'Besieged', excluded = T{true} },
	[258] = { name = 'Illusion', excluded = T{true} },
	[259] = { name = 'Encumbrance', excluded = T{true} },
	[260] = { name = 'Obliviscence', excluded = T{true} },
	[261] = { name = 'Impairment', excluded = T{true} },
	[262] = { name = 'Omerta', excluded = T{true} },
	[263] = { name = 'Debilitation', excluded = T{true} },
	[264] = { name = 'Pathos', excluded = T{true} },
	[265] = { name = 'Flurry', excluded = T{false} },
	[266] = { name = 'Concentration', excluded = T{true} },
	[267] = { name = 'Allied Tags', excluded = T{true} },
	[268] = { name = 'Sigil', excluded = T{true} },
	[269] = { name = 'Level Sync', excluded = T{true} },
	[270] = { name = 'Aftermath: Lv.1', excluded = T{false} },
	[271] = { name = 'Aftermath: Lv.2', excluded = T{false} },
	[272] = { name = 'Aftermath: Lv.3', excluded = T{false} },
	[273] = { name = 'Aftermath', excluded = T{false} },
	[274] = { name = 'Enlight', excluded = T{true} },
	[275] = { name = 'Auspice', excluded = T{false} },
	[276] = { name = 'Confrontation', excluded = T{true} },
	[277] = { name = 'Enfire II', excluded = T{true} },
	[278] = { name = 'Enblizzard II', excluded = T{true} },
	[279] = { name = 'Enaero II', excluded = T{true} },
	[280] = { name = 'Enstone II', excluded = T{true} },
	[281] = { name = 'Enthunder II', excluded = T{true} },
	[282] = { name = 'Enwater II', excluded = T{true} },
	[283] = { name = 'Perfect Defense', excluded = T{false} },
	[284] = { name = 'Egg', excluded = T{true} },
	[285] = { name = 'Visitant', excluded = T{true} },
	[286] = { name = 'Baramnesia', excluded = T{false} },
	[287] = { name = 'Atma', excluded = T{true} },
	[288] = { name = 'Endark', excluded = T{true} },
	[289] = { name = 'Enmity Boost', excluded = T{true} },
	[290] = { name = 'Subtle Blow Plus', excluded = T{true} },
	[291] = { name = 'Enmity Down', excluded = T{true} },
	[292] = { name = 'Pennant', excluded = T{true} },
	[293] = { name = 'Negate Petrify', excluded = T{true} },
	[294] = { name = 'Negate Terror', excluded = T{true} },
	[295] = { name = 'Negate Amnesia', excluded = T{true} },
	[296] = { name = 'Negate Doom', excluded = T{true} },
	[297] = { name = 'Negate Poison', excluded = T{true} },
	[298] = { name = 'Critical hit evasion down', excluded = T{false} },
	[299] = { name = 'Overload', excluded = T{true} },
	[300] = { name = 'Fire Maneuver', excluded = T{true} },
	[301] = { name = 'Ice Maneuver', excluded = T{true} },
	[302] = { name = 'Wind Maneuver', excluded = T{true} },
	[303] = { name = 'Earth Maneuver', excluded = T{true} },
	[304] = { name = 'Thunder Maneuver', excluded = T{true} },
	[305] = { name = 'Water Maneuver', excluded = T{true} },
	[306] = { name = 'Light Maneuver', excluded = T{true} },
	[307] = { name = 'Dark Maneuver', excluded = T{true} },
	[308] = { name = 'Double-Up Chance', excluded = T{false} },
	[309] = { name = 'Bust', excluded = T{false} },
	[310] = { name = 'Fighter\'s Roll', excluded = T{false} },
	[311] = { name = 'Monk\'s Roll', excluded = T{false} },
	[312] = { name = 'Healer\'s Roll', excluded = T{false} },
	[313] = { name = 'Wizard\'s Roll', excluded = T{false} },
	[314] = { name = 'Warlock\'s Roll', excluded = T{false} },
	[315] = { name = 'Rogue\'s Roll', excluded = T{false} },
	[316] = { name = 'Gallant\'s Roll', excluded = T{false} },
	[317] = { name = 'Chaos Roll', excluded = T{false} },
	[318] = { name = 'Beast Roll', excluded = T{false} },
	[319] = { name = 'Choral Roll', excluded = T{false} },
	[320] = { name = 'Hunter\'s Roll', excluded = T{false} },
	[321] = { name = 'Samurai Roll', excluded = T{false} },
	[322] = { name = 'Ninja Roll', excluded = T{false} },
	[323] = { name = 'Drachen Roll', excluded = T{false} },
	[324] = { name = 'Evoker\'s Roll', excluded = T{false} },
	[325] = { name = 'Magus\'s Roll', excluded = T{false} },
	[326] = { name = 'Corsair\'s Roll', excluded = T{false} },
	[327] = { name = 'Puppet Roll', excluded = T{false} },
	[328] = { name = 'Dancer\'s Roll', excluded = T{false} },
	[329] = { name = 'Scholar\'s Roll', excluded = T{false} },
	[330] = { name = 'Bolter\'s Roll', excluded = T{false} },
	[331] = { name = 'Caster\'s Roll', excluded = T{false} },
	[332] = { name = 'Courser\'s Roll', excluded = T{false} },
	[333] = { name = 'Blitzer\'s Roll', excluded = T{false} },
	[334] = { name = 'Tactician\'s Roll', excluded = T{false} },
	[335] = { name = 'Allies\'s Roll', excluded = T{false} },
	[336] = { name = 'Miser\'s Roll', excluded = T{false} },
	[337] = { name = 'Companion\'s Roll', excluded = T{false} },
	[338] = { name = 'Avenger\'s Roll', excluded = T{false} },
	[339] = { name = 'Naturalist\'s Roll', excluded = T{false} },
	[340] = { name = 'Warrior\'s Charge', excluded = T{true} },
	[341] = { name = 'Formless Strikes', excluded = T{true} },
	[342] = { name = 'Assassin\'s Charge', excluded = T{true} },
	[343] = { name = 'Feint', excluded = T{true} },
	[344] = { name = 'Fealty', excluded = T{true} },
	[345] = { name = 'Dark Seal', excluded = T{true} },
	[346] = { name = 'Diabolic Eye', excluded = T{true} },
	[347] = { name = 'Nightingale', excluded = T{true} },
	[348] = { name = 'Troubadour', excluded = T{true} },
	[349] = { name = 'Killer Instinct', excluded = T{true} },
	[350] = { name = 'Stealth Shot', excluded = T{true} },
	[351] = { name = 'Flashy Shot', excluded = T{true} },
	[352] = { name = 'Sange', excluded = T{true} },
	[353] = { name = 'Hasso', excluded = T{true} },
	[354] = { name = 'Seigan', excluded = T{true} },
	[355] = { name = 'Convergence', excluded = T{true} },
	[356] = { name = 'Diffusion', excluded = T{false} },
	[357] = { name = 'Snake Eye', excluded = T{true} },
	[358] = { name = 'Light Arts', excluded = T{true} },
	[359] = { name = 'Dark Arts', excluded = T{true} },
	[360] = { name = 'Penury', excluded = T{true} },
	[361] = { name = 'Parsimony', excluded = T{true} },
	[362] = { name = 'Celerity', excluded = T{true} },
	[363] = { name = 'Alacrity', excluded = T{true} },
	[364] = { name = 'Rapture', excluded = T{true} },
	[365] = { name = 'Ebullience', excluded = T{true} },
	[366] = { name = 'Accession', excluded = T{true} },
	[367] = { name = 'Manifestation', excluded = T{true} },
	[368] = { name = 'Drain Samba', excluded = T{false} },
	[369] = { name = 'Aspir Samba', excluded = T{false} },
	[370] = { name = 'Haste Samba', excluded = T{false} },
	[371] = { name = 'Velocity Shot', excluded = T{true} },
	[375] = { name = 'Building Flourish', excluded = T{true} },
	[376] = { name = 'Trance', excluded = T{false} },
	[377] = { name = 'Tabula Rasa', excluded = T{false} },
	[378] = { name = 'Drain Daze', excluded = T{false} },
	[379] = { name = 'Aspir Daze', excluded = T{false} },
	[380] = { name = 'Haste Daze', excluded = T{false} },
	[381] = { name = 'Finishing Move 1', excluded = T{true} },
	[382] = { name = 'Finishing Move 2', excluded = T{true} },
	[383] = { name = 'Finishing Move 3', excluded = T{true} },
	[384] = { name = 'Finishing Move 4', excluded = T{true} },
	[385] = { name = 'Finishing Move 5', excluded = T{true} },
	[386] = { name = 'Lethargic Daze 1', excluded = T{false} },
	[387] = { name = 'Lethargic Daze 2', excluded = T{false} },
	[388] = { name = 'Lethargic Daze 3', excluded = T{false} },
	[389] = { name = 'Lethargic Daze 4', excluded = T{false} },
	[390] = { name = 'Lethargic Daze 5', excluded = T{false} },
	[391] = { name = 'Sluggish Daze 1', excluded = T{false} },
	[392] = { name = 'Sluggish Daze 2', excluded = T{false} },
	[393] = { name = 'Sluggish Daze 3', excluded = T{false} },
	[394] = { name = 'Sluggish Daze 4', excluded = T{false} },
	[395] = { name = 'Sluggish Daze 5', excluded = T{false} },
	[396] = { name = 'Weakened Daze 1', excluded = T{false} },
	[397] = { name = 'Weakened Daze 2', excluded = T{false} },
	[398] = { name = 'Weakened Daze 3', excluded = T{false} },
	[399] = { name = 'Weakened Daze 4', excluded = T{false} },
	[400] = { name = 'Weakened Daze 5', excluded = T{false} },
	[401] = { name = 'Addendum: White', excluded = T{true} },
	[402] = { name = 'Addendum: Black', excluded = T{true} },
	[403] = { name = 'Reprisal', excluded = T{true} },
	[404] = { name = 'Magic Evasion Down', excluded = T{false} },
	[405] = { name = 'Retaliation', excluded = T{true} },
	[406] = { name = 'Footwork', excluded = T{true} },
	[407] = { name = 'Klimaform', excluded = T{true} },
	[408] = { name = 'Sekkanoki', excluded = T{true} },
	[409] = { name = 'Pianissimo', excluded = T{true} },
	[410] = { name = 'Saber Dance', excluded = T{false} },
	[411] = { name = 'Fan Dance', excluded = T{false} },
	[412] = { name = 'Altruism', excluded = T{true} },
	[413] = { name = 'Focalization', excluded = T{true} },
	[414] = { name = 'Tranquility', excluded = T{true} },
	[415] = { name = 'Equanimity', excluded = T{true} },
	[416] = { name = 'Enlightenment', excluded = T{true} },
	[417] = { name = 'Afflatus Solace', excluded = T{true} },
	[418] = { name = 'Afflatus Misery', excluded = T{true} },
	[419] = { name = 'Composure', excluded = T{true} },
	[420] = { name = 'Yonin', excluded = T{true} },
	[421] = { name = 'Innin', excluded = T{true} },
	[422] = { name = 'Carbuncle\'s Favor', excluded = T{false} },
	[423] = { name = 'Ifrit\'s Favor', excluded = T{false} },
	[424] = { name = 'Shiva\'s Favor', excluded = T{false} },
	[425] = { name = 'Garuda\'s Favor', excluded = T{false} },
	[426] = { name = 'Titan\'s Favor', excluded = T{false} },
	[427] = { name = 'Ramuh\'s Favor', excluded = T{false} },
	[428] = { name = 'Leviathan\'s Favor', excluded = T{false} },
	[429] = { name = 'Fenrir\'s Favor', excluded = T{false} },
	[430] = { name = 'Diabolos\'s Favor', excluded = T{false} },
	[431] = { name = 'Avatar\'s Favor', excluded = T{false} },
	[432] = { name = 'Multi Strikes', excluded = T{true} },
	[433] = { name = 'Double Shot', excluded = T{true} },
	[434] = { name = 'Transcendency', excluded = T{true} },
	[435] = { name = 'Restraint', excluded = T{true} },
	[436] = { name = 'Perfect Counter', excluded = T{true} },
	[437] = { name = 'Mana Wall', excluded = T{true} },
	[438] = { name = 'Divine Emblem', excluded = T{true} },
	[439] = { name = 'Nether Void', excluded = T{true} },
	[440] = { name = 'Sengikori', excluded = T{true} },
	[441] = { name = 'Futae', excluded = T{true} },
	[442] = { name = 'Presto', excluded = T{true} },
	[443] = { name = 'Climactic Flourish', excluded = T{true} },
	[444] = { name = 'Copy Image (2)', excluded = T{false} },
	[445] = { name = 'Copy Image (3)', excluded = T{false} },
	[446] = { name = 'Copy Image (4+)', excluded = T{false} },
	[447] = { name = 'Multi Shots', excluded = T{true} },
	[448] = { name = 'Bewildered Daze 1', excluded = T{false} },
	[449] = { name = 'Bewildered Daze 2', excluded = T{false} },
	[450] = { name = 'Bewildered Daze 3', excluded = T{false} },
	[451] = { name = 'Bewildered Daze 4', excluded = T{false} },
	[452] = { name = 'Bewildered Daze 5', excluded = T{false} },
	[453] = { name = 'Divine Caress', excluded = T{true} },
	[454] = { name = 'Saboteur', excluded = T{true} },
	[455] = { name = 'Tenuto', excluded = T{true} },
	[456] = { name = 'Spur', excluded = T{true} },
	[457] = { name = 'Efflux', excluded = T{true} },
	[458] = { name = 'Earthen Armor', excluded = T{false} },
	[459] = { name = 'Divine Caress', excluded = T{false} },
	[460] = { name = 'Blood Rage', excluded = T{true} },
	[461] = { name = 'Impetus', excluded = T{true} },
	[462] = { name = 'Conspirator', excluded = T{true} },
	[463] = { name = 'Sepulcher', excluded = T{true} },
	[464] = { name = 'Arcane Crest', excluded = T{false} },
	[465] = { name = 'Hamanoha', excluded = T{false} },
	[466] = { name = 'Dragon Breaker', excluded = T{false} },
	[467] = { name = 'Triple Shot', excluded = T{true} },
	[468] = { name = 'Striking Flourish', excluded = T{true} },
	[469] = { name = 'Perpetuance', excluded = T{true} },
	[470] = { name = 'Immanence', excluded = T{true} },
	[471] = { name = 'Migawari', excluded = T{true} },
	[472] = { name = 'Ternary Flourish', excluded = T{true} },
	[473] = { name = 'Muddle', excluded = T{true} },
	[474] = { name = 'Prowess', excluded = T{true} },
	[475] = { name = 'Voidwatcher', excluded = T{true} },
	[476] = { name = 'Ensphere', excluded = T{true} },
	[477] = { name = 'Sacrosanctity', excluded = T{true} },
	[478] = { name = 'Palisade', excluded = T{true} },
	[479] = { name = 'Scarlet Delirium', excluded = T{true} },
	[480] = { name = 'Scarlet Delirium', excluded = T{true} },
	[481] = { name = 'Abdhaljs Seal', excluded = T{true} },
	[482] = { name = 'Decoy Shot', excluded = T{true} },
	[483] = { name = 'Hagakure', excluded = T{true} },
	[484] = { name = 'Issekigan', excluded = T{true} },
	[485] = { name = 'Unbridled Learning', excluded = T{true} },
	[486] = { name = 'Counter Boost', excluded = T{true} },
	[487] = { name = 'Endrain', excluded = T{true} },
	[488] = { name = 'Enaspir', excluded = T{true} },
	[489] = { name = 'Afterglow', excluded = T{true} },
	[490] = { name = 'Brazen Rush', excluded = T{false} },
	[491] = { name = 'Inner Strength', excluded = T{false} },
	[492] = { name = 'Asylum', excluded = T{false} },
	[493] = { name = 'Subtle Sorcery', excluded = T{false} },
	[494] = { name = 'Stymie', excluded = T{false} },
	[496] = { name = 'Intervene', excluded = T{false} },
	[497] = { name = 'Soul Enslavement', excluded = T{false} },
	[498] = { name = 'Unleash', excluded = T{false} },
	[499] = { name = 'Clarion Call', excluded = T{false} },
	[500] = { name = 'Overkill', excluded = T{false} },
	[501] = { name = 'Yaegasumi', excluded = T{false} },
	[502] = { name = 'Mikage', excluded = T{false} },
	[503] = { name = 'Fly High', excluded = T{false} },
	[504] = { name = 'Astral Conduit', excluded = T{false} },
	[505] = { name = 'Unbridled Wisdom', excluded = T{false} },
	[507] = { name = 'Grand Pas', excluded = T{false} },
	[508] = { name = 'Widened Compass', excluded = T{false} },
	[509] = { name = 'Odyllic Subterfuge', excluded = T{false} },
	[510] = { name = 'Ergon Might', excluded = T{true} },
	[511] = { name = 'Reive Mark', excluded = T{true} },
	[512] = { name = 'Ionis', excluded = T{true} },
	[513] = { name = 'Bolster', excluded = T{false} },
	[515] = { name = 'Lasting Emanation', excluded = T{true} },
	[516] = { name = 'Ecliptic Attrition', excluded = T{true} },
	[517] = { name = 'Collimated Fervor', excluded = T{true} },
	[518] = { name = 'Dematerialize', excluded = T{true} },
	[519] = { name = 'Theurgic Focus', excluded = T{true} },
	[522] = { name = 'Elemental Sforzo', excluded = T{false} },
	[523] = { name = 'Ignis', excluded = T{true} },
	[524] = { name = 'Gelus', excluded = T{true} },
	[525] = { name = 'Flabra', excluded = T{true} },
	[526] = { name = 'Tellus', excluded = T{true} },
	[527] = { name = 'Sulpor', excluded = T{true} },
	[528] = { name = 'Unda', excluded = T{true} },
	[529] = { name = 'Lux', excluded = T{true} },
	[530] = { name = 'Tenebrae', excluded = T{true} },
	[531] = { name = 'Vallation', excluded = T{true} },
	[532] = { name = 'Swordplay', excluded = T{true} },
	[533] = { name = 'Pflug', excluded = T{true} },
	[534] = { name = 'Embolden', excluded = T{true} },
	[535] = { name = 'Valiance', excluded = T{true} },
	[536] = { name = 'Gambit', excluded = T{true} },
	[537] = { name = 'Liement', excluded = T{true} },
	[538] = { name = 'One for All', excluded = T{false} },
	[539] = { name = 'Regen', excluded = T{false} },
	[540] = { name = 'Poison II', excluded = T{false} },
	[541] = { name = 'Refresh II', excluded = T{false} },
	[542] = { name = 'STR Boost', excluded = T{true} },
	[543] = { name = 'DEX Boost', excluded = T{true} },
	[544] = { name = 'VIT Boost', excluded = T{true} },
	[545] = { name = 'AGI Boost', excluded = T{true} },
	[546] = { name = 'INT Boost', excluded = T{true} },
	[547] = { name = 'MND Boost', excluded = T{true} },
	[548] = { name = 'CHR Boost', excluded = T{true} },
	[549] = { name = 'Attack Boost', excluded = T{true} },
	[550] = { name = 'Defense Boost', excluded = T{true} },
	[551] = { name = 'Magic Atk. Boost', excluded = T{true} },
	[552] = { name = 'Magic Def. Boost', excluded = T{true} },
	[553] = { name = 'Accuracy Boost', excluded = T{true} },
	[554] = { name = 'Evasion Boost', excluded = T{true} },
	[555] = { name = 'Magic Acc. Boost', excluded = T{true} },
	[556] = { name = 'Magic Evasion Boost', excluded = T{true} },
	[557] = { name = 'Attack Down', excluded = T{false} },
	[558] = { name = 'Defense Down', excluded = T{false} },
	[559] = { name = 'Magic Atk. Down', excluded = T{false} },
	[560] = { name = 'Magic Def. Down', excluded = T{false} },
	[561] = { name = 'Accuracy Down', excluded = T{false} },
	[562] = { name = 'Evasion Down', excluded = T{false} },
	[563] = { name = 'Magic Acc. Down', excluded = T{false} },
	[564] = { name = 'Magic Evasion Down', excluded = T{false} },
	[565] = { name = 'Slow II', excluded = T{false} },
	[566] = { name = 'Paralysis II', excluded = T{false} },
	[567] = { name = 'Weight II', excluded = T{false} },
	[568] = { name = 'Foil', excluded = T{true} },
	[569] = { name = 'Blaze of Glory', excluded = T{true} },
	[570] = { name = 'Battuta', excluded = T{true} },
	[571] = { name = 'Rayke', excluded = T{true} },
	[572] = { name = 'Avoidance Down', excluded = T{false} },
	[573] = { name = 'Deluge Spikes', excluded = T{true} },
	[574] = { name = 'Fast Cast', excluded = T{true} },
	[575] = { name = 'gestation', excluded = T{true} },
	[576] = { name = 'Doubt', excluded = T{true} },
	[577] = { name = 'Cait Sith\'s Favor', excluded = T{false} },
	[578] = { name = 'Fishy Intuition', excluded = T{true} },
	[579] = { name = 'Commitment', excluded = T{true} },
	[580] = { name = 'Haste II', excluded = T{false} },
	[581] = { name = 'Flurry II', excluded = T{false} },
	[582] = { name = 'Contradance', excluded = T{true} },
	[583] = { name = 'Apogee', excluded = T{true} },
	[584] = { name = 'Entrust', excluded = T{true} },
	[585] = { name = 'Costume', excluded = T{true} },
	[586] = { name = 'Curing Conduit', excluded = T{true} },
	[587] = { name = 'TP Bonus', excluded = T{true} },
	[588] = { name = 'Finishing Move (6+)', excluded = T{true} },
	[589] = { name = 'Firestorm II', excluded = T{true} },
	[590] = { name = 'Hailstorm II', excluded = T{true} },
	[591] = { name = 'Windstorm II', excluded = T{true} },
	[592] = { name = 'Sandstorm II', excluded = T{true} },
	[593] = { name = 'Thunderstorm II', excluded = T{true} },
	[594] = { name = 'Rainstorm II', excluded = T{true} },
	[595] = { name = 'Aurorastorm II', excluded = T{true} },
	[596] = { name = 'Voidstorm II', excluded = T{true} },
	[597] = { name = 'Inundation', excluded = T{true} },
	[598] = { name = 'Cascade', excluded = T{true} },
	[599] = { name = 'Consume Mana', excluded = T{true} },
	[600] = { name = 'Runeist\'s Roll', excluded = T{false} },
	[601] = { name = 'Crooked Cards', excluded = T{true} },
	[602] = { name = 'Vorseal', excluded = T{true} },
	[603] = { name = 'Elvorseal', excluded = T{true} },
	[604] = { name = 'Mighty Guard', excluded = T{false} },
	[605] = { name = 'Gale Spikes', excluded = T{true} },
	[606] = { name = 'Clod Spikes', excluded = T{true} },
	[607] = { name = 'Glint Spikes', excluded = T{true} },
	[608] = { name = 'Negate Virus', excluded = T{true} },
	[609] = { name = 'Negate Curse', excluded = T{true} },
	[610] = { name = 'Negate Charm', excluded = T{true} },
	[611] = { name = 'Magic Evasion Boost', excluded = T{true} },
	[612] = { name = 'Colure Active', excluded = T{true} },
	[613] = { name = 'Mumor\'s Radiance', excluded = T{true} },
	[614] = { name = 'Ullegore\'s Gloom', excluded = T{true} },
	[615] = { name = 'Boost', excluded = T{true} },
	[616] = { name = 'Artisanal Knowledge', excluded = T{true} },
	[617] = { name = 'Sacrifice', excluded = T{true} },
	[618] = { name = 'Emporox\'s Gift', excluded = T{true} },
	[619] = { name = 'Spirit Bond', excluded = T{true} },
	[620] = { name = 'Awaken', excluded = T{true} },
	[621] = { name = 'Majesty', excluded = T{true} },
	[622] = { name = 'Guarding Rate Boost', excluded = T{true} },
	[623] = { name = 'Rampart', excluded = T{false} },
	[624] = { name = 'Wind', excluded = T{true} },
	[625] = { name = 'Siren', excluded = T{true} },
	[626] = { name = 'Negate Sleep', excluded = T{faltruese} },
	[627] = { name = 'Mobilization', excluded = T{true} },
	[628] = { name = 'Hover Shot', excluded = T{true} },
	[629] = { name = 'Moogle Amplifier', excluded = T{true} },
	[630] = { name = 'taint', excluded = T{true} },
	[631] = { name = 'haunt', excluded = T{true} },
};